### ISSUE TITLE
Captive portal

### ISSUE THREAD

**Issue by rob040** [cotestatnt/async-esp-fs-webserver#11]
With your release 1.0.3, you added simpleServerCaptive.ino and I was testing with this. 
It unfortunately did not work, as it tries to open https://192.168.4.1/Setup on my smartphone; there is no https support here.
So, I tried to force the redirect string to http://192.168.4.1/Setup in the example with:

```c++
myIP = WiFi.softAPIP();
String redirect = String("http://")+myIP.toString()+String("/setup");
server.startCaptivePortal("ESP_AP", "123456789", redirect.c_str());
``` 
but that resulted in failure and following logging:
```
[I][CaptiverPortal.hpp:46] handleRequest():	Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://8.8.8.8http://192.168.4.1/setup
[I][CaptiverPortal.hpp:46] handleRequest():	Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://8.8.8.8http://192.168.4.1/setup
[I][CaptiverPortal.hpp:46] handleRequest():	Captive handler triggered. Requested app.rundefit.com/api/system/open/collect -> redirecting to http://8.8.8.8http://192.168.4.1/setup
[I][CaptiverPortal.hpp:46] handleRequest():	Captive handler triggered. Requested 8.8.8.8http//192.168.4.1/setup -> redirecting to http://8.8.8.8http://192.168.4.1/setup
[I][CaptiverPortal.hpp:46] handleRequest():	Captive handler triggered. Requested 8.8.8.8http//192.168.4.1/setup -> redirecting to http://8.8.8.8http://192.168.4.1/setup
[I][CaptiverPortal.hpp:46] handleRequest():	Captive handler triggered. Requested 8.8.8.8http//192.168.4.1/setup -> redirecting to http://8.8.8.8http://192.168.4.1/setup
[I][CaptiverPortal.hpp:46] handleRequest():	Captive handler triggered. Requested 8.8.8.8http//192.168.4.1/setup -> redirecting to http://8.8.8.8http://192.168.4.1/setup
```
So, the CaptiverPortal.hpp (Shouldn't be called CaptivePortal.hpp ?) CaptiveRequestHandler class C'tor gets changed Wifi ip and host url upon each request.
The logging looks promising:
```
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested play.googleapis.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested connectivitycheck.gstatic.com/generate_204 -> redirecting to http://192.168.4.1/setup
[I][CaptiverPortal.hpp:47] handleRequest():.Captive handler triggered. Requested play.googleapis.com/generate_204 -> redirecting to http://192.168.4.1/setup
```
All requests are redirected to the IP address of the AP, however the sign-in page on my phone stays empty and finally shows connection timeout.
Looking at the AP details, the AP now has IP address 8.8.8.9, so the earlier attempt to connect to http://8.8.8.8/... might be the right way...

to be continued.

**Comment by rob040** [comment]
I just saw you pushed changes for version 1.0.4, testing that.

**Comment by rob040** [comment]
The captive portal working in version 1.0.4. The setup page is shown and new credentials can be entered.
Logging shows that the ESP connects to the new WIFI network, however the captive portal is still active, and setup page is still serviced. A forced remote restart from setup page update & FS menu is needed.
Only after that serial logging shows a restart and reconnect to setup page is possible. Only then the scan wifi networks button does something.

```
[I][AsyncFsWebServer.cpp:385] handleScanNetworks():.Start scan WiFi networks
[I][AsyncFsWebServer.cpp:387] handleScanNetworks():. done!
Number of networks: -2
```

**Comment by rob040** [comment]
One more point.
After entering the new wifi credentials, and this is succesful, there is a popup, there is a popup with a link to "the new LAN address", however, the new lan address is not visible, and holding my finger (on smartphone screen), the text is very tiny (~3x8mm?) and disappears under my finger.

**Comment by rob040** [comment]
related to wifi, but not captiveportal.

request from:
.  http://192.168.2.121/wifistatus
returns:
.  {"firmware": "22:28:00", "mode":"Station", "ip":2030217408}

the ip address is 32-bit value in little endian byte order. This is not portable; network byte order, e.g. IP stack, is big endian.
Expected: string "192.168.2.121"

Question: Could "firmware" also include the library version?

**Comment by cotestatnt** [comment]
Hi @rob040 and first of all, thanks for your collaboration on this library!

I tried to include many of your suggestions (also from other issues), have you had a chance to try them?
As for the string reported as firmware, you can customize it using the method `setFirmwareVersion();`

The maximum length of the string is limited to 15 characters because it seems enough at the time. Eventually it is possible to add the possibility of re-allocating memory if necessary,

**Comment by rob040** [comment]
Hi @cotestatnt, thanks for the confidence. I will help and improve wherever I can. I have a few projects in the works and at least one older project that I like to use this library for, to get them a better responsive web page and OTA functionality.

I've tried the captive portal again; it kind of works, but not satisfied with behaviour. I think a device restart will fix that, but the client webbrowser, usually a smartphone, should have been redirected to the already known and shown IP address. The disappearance of the ESP AP will (should) cause the smartphone wifi to re-activate its normal wifi connection and connect to same LAN as the ESP is connected to.

wrt. firmware version, it would be nice if the library version was included in the default firmware version, shown in the example apps. However there is no getter function for the user application to get library version to be able to present that. The user application is indeed able to use the setFirmwareVersion() to show its version in the setup page. 
Having the library version presented in any API, would mean that upon release, you have a bit more work of updating the version number on at least two places, adding the possibility of making mistakes.

Did you notice I changed `strncpy` into `strlcpy` ; it is safer in assuring zero termination the string regardless of the supplied string length. I did not check if there are multiple occurrences of that. 
A fw version length of 15 chars is IMO plenty enough.

**Comment by rob040** [comment]
One other issue I ran into while testing with ESP8266, is that OTA download result in exception. I'll try to investigate further and get at least more details, then enter an issue here to get that tracked.

**Comment by cotestatnt** [comment]
>Having the library version presented in any API

It's quite easy to implement, but it would be great to find a way that automatically retrieves information from the library.properties file. If I add a simple `#define` in the source, I'm sure I'll forget to update it every time :pensive:

Regarding the issue with ESP8266, I've noticed the same behaviuor. I've tried to mess with ESP8266 WDT, but with no lucky.
I would like to leave support for this mcu, but I won't deny that for me it is of secondary importance because I never use it in my projects.

**Comment by cotestatnt** [comment]
Hi @rob040 

I've added the method `const char* getVersion();`
The definition of method is inside a distinct file named `version.cpp`.
In this way I can automatically update the content of file with a workflow which reads current library version value from `library.properties` on each push
