### ISSUE TITLE
Setup page small issues

### ISSUE THREAD

**Issue by rob040** [cotestatnt/async-esp-fs-webserver#19]
Hi Tolentino, upon further testing I noticed on the setup page that the save icon is missing on the update&FS tab save button, while it is visible on the WiFi setup page when (once(!)) the manual-config switch is set.
Also, on that WiFi setup page, the store-WiFi-credentials switch is differently styled than the other switch; I expect it should use input-label class instead of lbl-wifi class.

I'll supply an PR to show my fixes.

Other observations:
- File save in the Ace editor is unreliable hit-miss; sometimes it stays busy for long time and never finishes. lost some update that way. On serial console I see AsyncTcp _poll() rx timeout. The file write does not complete ever. 
- I thought I could download a file from the Ace editor file list, but now this option is not offered
- In Ace editor, especially on touch interface (smartphone), it is all to easy to delete a file; it is just below the touch point after a little longer press and there is no confirmation dialog.
- on my esp32 devkit I see the the BUILDIN-LED (GPIO02) fast and irregular blinking. Looks like some debug output of some 100ms task and another task, but I didn't find reference to it.

**Comment by cotestatnt** [comment]
Good Morning @rob040 
The icon missing now should be fixed. I've commented you pull request https://github.com/cotestatnt/async-esp-fs-webserver/pull/20 with the reasons why I haven't megerd it yet.

I've updated also the /edit web page adding "Download" right click handler and confirm message for file deleting
