### ISSUE TITLE
Feature : Add option to remove default "setup tab"

### ISSUE THREAD

**Issue by GregAscolab** [cotestatnt/async-esp-fs-webserver#24]
**Feature**  
Add `#define` to activate/remove default "setup tab" (Wifi / update & FS)  

**Description / Use case**  
I will mainly use my ESP wifi "access point" to connect to in order to display webpage for setup, hmi, etc...  
And I don't want user to be able to change wifi parameter or scan...  

So I asking myself if there is a possibility to add some kind of #define to remove native features...  

This will be interresting also if some user don't want the firmware update feature.  

**Bonus**  
An update of this demand could also be to be able to define web page acces according some kind of user logging...  
I user is not logged : display only  
if logged : access to setup and modification.  

Maybe this could be done by "javascript framework" or something (html/javascript is not my main knowledge ;-) )

**Comment by cotestatnt** [comment]
I had already thought of something like this, let's say it's on my to-do list.

For now, you could work around the problem by setting a password that only you know to access the `/setup` page
The `/edit` page, however, must be explicitly enabled, so you just need not enter the relevant instructions.
A complete example in [customOptions.ino](https://github.com/cotestatnt/async-esp-fs-webserver/blob/master/examples/customOptions/customOptions.ino#L185)

```
  // Enable ACE FS file web editor and add FS info callback function
  // server.enableFsCodeEditor();

  // set /setup and /edit page authentication
  server.setAuthentication("admin", "admin");
```

**Comment by GregAscolab** [comment]
> I had already thought of something like this, let's say it's on my to-do list.
> 
> For now, you could work around the problem by setting a password that only you know to access the `/setup` page

Yes I understand... but I'm not the only user so I need to share password (not so good...)  

In my case, I really need Firmware update, Options tabs... but not the wifi setup part.  
Maybe I can make my own "setup" html page, removing "Wifi" part ?

> The `/edit` page, however, must be explicitly enabled, so you just need not enter the relevant instructions.

How to enable/disable the "/edit" page ? : 

Using `INCLUDE_EDIT_HTM` ?
Using `server.enableFsCodeEditor();` ?

**Comment by GregAscolab** [comment]
Thank you very much for this "hack" !
I'm currently changing `/setup` page to my look and feel, and just "hidding" wifi info.
But your javascript solution is much more clean to be able to reactivate wifi option later...

Creating a new setup page is also a solution I was thinking of... it will depend on my code size/memory available...
