### ISSUE TITLE
How can I read the constructor parameter from the config.json?

### ISSUE THREAD

**Issue by cdmaxy** [cotestatnt/async-esp-fs-webserver#26]
Hello,
I think your work is very beautiful! I also included it in my project to get to know and play with.

I would like to make the port and hostname dynamic and read them from the config.json when booting up. 
From `AsyncFsWebServer server(80, LittleFS, "myHostname");`
I would like `AsyncFsWebServer server(); `or `AsyncFsWebServer server;` have. 
Because all parameters should be read from the config.json.

Methods like `server.setHosname("myHostname");`
or `server.setPort();`
would be nice.

**Comment by cotestatnt** [comment]
Hello @cdmaxy and thank you for your interest in this project.

Unfortunately in the _ESPAsyncWebServer_ library on which mine is based, the webserver port must be defined during the declaration and there are no methods to modify it at runtime.

The hostname parameter is something I added and so I could easily implement what you ask, but for the port it is more complex.

At this point I would recommend you switch to the [same library,](https://github.com/cotestatnt/esp-fs-webserver) but based on the webserver included in the Arduino core.

In the latest versions I solved the "slowness" problem that plagued this library at beginning and now it is completely equivalent in terms of speed and reactivity. It consumes also less resources.
The WebServer class used in Arduino Core library, can be started passing also the port calling `begin(port_number)` method, so I can easily add the functionality you need.

**Comment by cdmaxy** [comment]
Thank you for the quick response! I'm looking forward to the implemented function! :-)

**Comment by cotestatnt** [comment]
Hi @cdmaxy 

As I mentioned, I have added this functionality to the library https://github.com/cotestatnt/esp-fs-webserver and therefore I am going to close this issue.

You have now the method `void setHostname(const char* host);` and the possibility to call the `begin(81)` method passing a port number as parameter

If you need, open a new one in the other repository please.
