### ISSUE TITLE
config/config.json does not start with /

### ISSUE THREAD

**Issue by cdmaxy** [cotestatnt/async-esp-fs-webserver#27]
Hallo,

I've detect possible error on set value by dialog "Simple Async ESP FS Webserver"
![2024-02-02 19_14_09-Simple Async ESP FS WebServer](https://github.com/cotestatnt/async-esp-fs-webserver/assets/61500950/ccaca3f5-7722-4ecf-a414-d7f1245d020b)

Error Code: 
```
2044358][W][AsyncTCP.cpp:974] _poll(): pcb is NULL
[2058398][E][vfs_api.cpp:29] open(): config does not start with /

[I][.pio/libdeps/nodemcu-32s/AsyncEspFsWebserver/src/AsyncFsWebServer.cpp:316] createDirFromPath():     Error. Folder config not created[2058409][E][vfs_api.cpp:29] open(): config/config.json does not start with /
```

**Comment by cotestatnt** [comment]
This bug should be fixed with latest release.
