### ISSUE TITLE
setup wifiscan and wificonnect button does not work with ESP8266 12E/12F

### ISSUE THREAD

**Issue by ldijkman** [cotestatnt/async-esp-fs-webserver#29]
setup wifiscan and wificonnect does not work with ESP8266 12E/12F

https://youtu.be/VG4Q86ob8IQ

**Comment by cotestatnt** [comment]
Seems tha wifiscan trigger the soft watchdog reset with ESP8266.
I will try to run it asyncrhonously.

**Comment by ldijkman** [comment]
Well still use your library
But now use improv for wifi provisioning after browser install
https://ldijkman.github.io/async-esp-fs-webserver/

**Comment by cotestatnt** [comment]
wifiscan bug fixed.
Now the network scanning is done asyncrhonously (both ESP8266 and ESP32).
