### ISSUE TITLE
SimpleServer example problem 

### ISSUE THREAD

**Issue by leevv66** [cotestatnt/async-esp-fs-webserver#3]
Hi, 

I'm trying to follow your SimpleServer example on Lilygo T-embed ESP32 S3 board. 
Program compiles but constantrly resboots on hardware with error: 
"Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled."

When I add hostname (third argument) into 
AsyncFsWebServer server(80, LittleFS); 

the problem gone.
Something to do with srncpy in AsyncFsWebServer.h ?

Regards
SL

**Comment by cotestatnt** [comment]
Hi @leevv66 

I'm sorry but the example need to be updated.
You need to pass also the hostname to class constructorm, it's not optional for the moment.


`AsyncFsWebServer server(80, LittleFS, "hostname");`
