### ISSUE TITLE
Git repo has a fixed bug which is still in the Arduino IDE library collection.

### ISSUE THREAD

**Issue by dionmes** [cotestatnt/async-esp-fs-webserver#40]
Hi,
I noticed a difference in the file AsyncEspFsWebserver.h between the git repository and the version in the Arduino ide library list. For me it caused an infinite reboot loop.
Code in the Arduino ide library collection (1.0.5):

  
    IPAddress startWiFi(uint32_t timeout, const char *apSSID, const char *apPsw, CallbackF fn=nullptr) {
      setAP(apSSID, apPsw, m_captiveIp);
      startWiFi(timeout, fn);
    }

Should be as in this git repo.

    IPAddress startWiFi(uint32_t timeout, const char *apSSID, const char *apPsw, CallbackF fn=nullptr) {
      setAP(apSSID, apPsw, m_captiveIp);
      return startWiFi(timeout, fn);
    }

**Comment by cotestatnt** [comment]
The method has been completely revised.

I am closing this issue because it no longer has a match in the source, if there are still problems with `startWifi()` please open a new issue.
