### ISSUE TITLE
Failed when trying to install the package

### ISSUE THREAD

**Issue by allyssonmast** [cotestatnt/async-esp-fs-webserver#5]
I get the error when trying to install the package:

"Failed to install library: 'AsyncEspFsWebserver:1.0.1'. No valid dependencies solution found: dependency 'ESPAsyncWebserver' is not available"

**Comment by cotestatnt** [comment]
Hello @allyssonmast  and thank you for your interest.
Yes, unfortunately, the library in question does not exist in the Arduino repository and therefore is not automatically retrieved.

In any case, I have included the sources directly in the src folder so you just need to install the async-esp-fs-webserver library and everything else comes accordingly.

I just committed, so you can directly download the zip file and manually add it to the Arduino IDE libraries folder.
Anyway, later I will create a new release.
