### ISSUE TITLE
AP not visible/starting after wrong ssid and psswd saved

### ISSUE THREAD

**Issue by mano1979** [cotestatnt/async-esp-fs-webserver#53]
In an attempt to force the accespoint to show up (for testing) i entered nonexistent wifi credentials. But now i cannot connect to the captive portal. Here is the serial output after a reset:
`ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40385368
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x1058
load:0x403cc710,len:0x8a8
load:0x403ce710,len:0x2fac
entry 0x403cc710

Listing directory: /
                    |__ FILE: app.js (14225 bytes)

                                                  Listing directory: /backup
                                                                            |__ FILE: favicon.ico (318 bytes)
                                                                                                             |__ FILE: index.htm (4580 bytes)

                     Listing directory: /config
                                               |__ FILE: config.json (52 bytes)

                                                                               Listing directory: /css
                                                                                                      |__ FILE: pico.fluid.classless.css.gz (5387 bytes)
                                |__ FILE: edit.min.htm (18401 bytes)
                                                                    |__ FILE: favicon.ico (318 bytes)

                                                                                                     Listing directory: /img
    |__ FILE: HammerLogo_trp.png (125848 bytes)
                                               |__ FILE: index.htm (4580 bytes)
                                                                               |__ FILE: setup.htm.gz (9499 bytes)
                                                                                                                  |__ FILE: setup.htm (42206 bytes)
                           |__ FILE: style.css (6773 bytes)
                                                           Connecting to testnetwork
.............................................................Timeout!

[I][AsyncFsWebServer.cpp:150] startCaptivePortal():     Captive portal started. Redirecting all requests to /setupTHE HAMMER network IP Address: 192.168.4.1
Open /setup page to configure optional parameters.
                                                  Open /edit page to view, edit or upload example or your custom webserver source files.
`

**Comment by mano1979** [comment]
I managed to fix it by changing this part of the AsyncFsWebserver.cpp file on line 125.

replace the if/else statement with this:

` m_captiveRun = false;
    if (strlen(pass)) {
        m_captiveRun = WiFi.softAP(ssid, pass);
        WiFi.setTxPower(WIFI_POWER_8_5dBm);
    } else {
        m_captiveRun = WiFi.softAP(ssid);
        WiFi.setTxPower(WIFI_POWER_8_5dBm);
    }`

After changing this, the acces point showed up again.

**Comment by mano1979** [comment]
Fixed!

**Comment by Quantummechanic1** [comment]
> I managed to fix it by changing this part of the AsyncFsWebserver.cpp file on line 125.
> 
> replace the if/else statement with this:
> 
> ` m_captiveRun = false; if (strlen(pass)) { m_captiveRun = WiFi.softAP(ssid, pass); WiFi.setTxPower(WIFI_POWER_8_5dBm); } else { m_captiveRun = WiFi.softAP(ssid); WiFi.setTxPower(WIFI_POWER_8_5dBm); }`
> 
> After changing this, the acces point showed up again.

So effectively you added `WiFi.setTxPower(WIFI_POWER_8_5dBm);`. Is this wifi TX power valid for ALL regions over the world? (each region has its own max transmit power defined)
The added statement `m_captiveRun = false;` has no use and is not affective.
