### ISSUE TITLE
Need ability to call a handler function after WIFI setup

### ISSUE THREAD

**Issue by micgresham** [cotestatnt/async-esp-fs-webserver#6]
When WiFi setup connects to a network via the /setup page, I need to be able to call a handler function to collect and store the SSID/PSK in my own config file.  I am not using the library config file.

**Comment by cotestatnt** [comment]
Hi @micgresham 

SSID and password are not stored in config file.
ESP MCUs has a dedicated part of flash memory for that and it's not possible handle from filesystem.

Check the class method [doWifiConnection()](https://github.com/cotestatnt/async-esp-fs-webserver/blob/master/src/AsyncFsWebServer.cpp#L454).

Anyway you can override the default callback method binded  to `/connect` endpoint with you own if you think you need it.

After calling the init() method, replace the current binding with your function
```
 server.init();
 server.on("/connect", HTTP_POST,  yourOwnFunction);
```

**Comment by micgresham** [comment]
got it.  I was hoping to replace the existing function and not add more code to the compiled image.
