### ISSUE TITLE
 customize /setup page (headers, logo etc etc)

### ISSUE THREAD

**Issue by Alex-LCH** [cotestatnt/async-esp-fs-webserver#9]
I generated a new "setup.h" with the following procedure, but there is no "finalize.js", where can I find this file? Thanks

1. [ok] edit the source files as your needs (setup.htm, app.js, style.css)
2. [ok ] put all togheter in the same all.htm file inside dist folder
3. [ok] open a terminal in dist folder and run npm i to install all nodejs modules needed
4. [NOK ] run node finalize.js 
5. [-- ] overwrite the content of setup_htm.h in src folder

**Comment by cotestatnt** [comment]
Hi @Alex-LCH 
I'm sorry, but the readme is related to an old version, I forgot to update it.

With the new version, you don't need to put all togheter and the script name is `minify.js`.
The script searches for the necessary files and updates the `all.htm` file automatically, minimizing the CSS and Javascript,
Then it creates a Gzip version of this file and this zipped version is transformed into a C-array

On Windows system you could use also this [SEGGER tool](https://www.segger.com/free-utilities/bin2c/), but you need to build the gzip file on your own doing manually all steps before and editing the name of C-array.

Unfortunately there is still something to fix and the first time the minify,js script doesn't do all the steps correctly, so the advice for now is to run it twice.

**Comment by Alex-LCH** [comment]
Thank you for your answer, by the way, which example is the following picture?

![218732999-e22fe092-cbc9-40d6-a34b-38282fbd60e2](https://github.com/cotestatnt/async-esp-fs-webserver/assets/12538574/1f740810-0ac7-4e7a-8a50-7dc76ea6ec44)

**Comment by Alex-LCH** [comment]
Thank you for your answer, by the way, which example with DHCP is? 
![218732999-e22fe092-cbc9-40d6-a34b-38282fbd60e2](https://github.com/cotestatnt/async-esp-fs-webserver/assets/12538574/9018ed14-ac94-4764-b808-26fa153a0b9e)

**Comment by Alex-LCH** [comment]
Thank you so much for your patience and selfless sharing!

**Comment by cotestatnt** [comment]
Good morning @Alex-LCH 
In the latest commits, I've added the support for WiFi manual configuration directly in the library itself.

**Comment by Alex-LCH** [comment]
Hello, thanks again for sharing, I tested version 1.0.4, but there is a small problem I don't know if it's my settings or not, it's that most of the manual ip addresses can't be saved to the config.json file
<img width="740" alt="截屏2024-01-07 23 12 43" src="https://github.com/cotestatnt/async-esp-fs-webserver/assets/12538574/eb1ff1c0-74d1-4a12-95c1-954b64683f1a">

**Comment by cotestatnt** [comment]
Hi @Alex-LCH 

Once you have entered your IP, gateway and subnet, press "Save Configuration" button before start WiFi connection. In this way, on the next restart that values should be as you inserted.

**Comment by cotestatnt** [comment]
I'm sorry, but I've just found a little bug.
Once you have inserted a value, subsequent changes to this value will not be saved.
I've already identified and fixed the bug, now I'll commit the changes.
